//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clima_Noticias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class climas
    {
        public int idclima { get; set; }
        public string ciudad { get; set; }
        public string temp { get; set; }
        public string temp_max { get; set; }
        public string temp_min { get; set; }
        public string humedad { get; set; }
        public int idciudad { get; set; }
    
        public virtual busquedas busquedas { get; set; }
    }
}
