//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clima_Noticias.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class climaEntities : DbContext
    {
        public climaEntities()
            : base("name=climaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<busquedas> busquedas { get; set; }
        public virtual DbSet<climas> climas { get; set; }
        public virtual DbSet<Endpo> Endpo { get; set; }
        public virtual DbSet<noticias> noticias { get; set; }
    }
}
